biblicon = {
	ficha : {
		constantes : {
			apellido 				: "Apellido(s)",
			nombre					: "Nombre(s)",
			apellido_otro 			: "Apellido(s)",
			nombre_otro   			: "Nombre(s)",
			titulo					: "Título",
			edicion_de				: "Edición de",
			traduccion				: "Traducción de",
			prologo					: "Prologo de",
			et_al					: "et al",
			edicion					: "Edición",
			otros_datos				: "Otros datos",
			editorial				: "Editorial",
			ciudad					: "Ciudad",
			ano						: "Año",
			coleccion				: "Colección",
			paginas					: "Páginas",
			biblioteca				: "Biblioteca",
			localizacion			: "Localización",
			notas					: "Notas",
			a						: "A",
			b						: "B",
			c						: "C",
			d						: "D",
			institucion				: "Institución",
			pagina_ini				: "Páginas de la",
			pagina_fin				: "a la",
			revista					: "Revista",
			tomo					: "Tomo",
			numero					: "Núm.",
			mes						: "Mes",
			semana					: "Semana",
			apellido_editor			: "Apellido(s)",
			nombre_editor			: "Nombre(s)",
			apellido_editor_otro 	: "Apellido(s)",
			nombre_editor_otro		: "Nombre(s)",
			et_al_editor			: "et al",
			periodico				: "Periódico",
			seccion					: "Sección",
			dia						: "Día",
			url						: "Dirección WWW",
			portal					: "Portal",
			fecha_acceso			: "Fecha de acceso",
			fecha_publicacion		: "Fecha de publicación",
			editor					: "Editor",
			titulo_libro			: "Título del libro",
			categoria				: "Categoria",
			tipo 					: "Tipo",
			catalogoTipo			:	{
				1 : "(ed.)",
				2 : "(coord.)",
				3 : "(comp.)",
				4 : "(dir.)"
			}
			
		}
	}
};